version: '3.8'

services:
  astrbot:
    image: soulter/astrbot:latest
    container_name: astrbot
    ports: 
      - "6000-6200:6000-6200"
      - "11451:11451"
    volumes:
      - ./data:/AstrBot/data
