name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write secret to file
        run: mkdir data & echo "$CMD_CONFIG" > data/cmd_config.json
        env:
          MY_SECRET: ${{ secrets.CMD_CONFIG }}

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install pytest pytest-cov pytest-asyncio

      - name: Run tests
        run: PYTHONPATH=./ pytest --cov=. tests/ -v

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}